### ISSUE TITLE
[Bug]Failed opening required '/var/www/vhosts/panel.site.com/httpdocs/modules/Serviceproxmox/vendor/autoload.php' 

### ISSUE THREAD

**Issue by sandwitcherz** [FOSSBilling/Proxmox#31]
**Describe the bug**
Installing module from admin panel on Linux ( plesk ), php 8.0.3, plugin  Proxmox 0.1.0
and i don't know where to download the 'pmxconfig' folder...

**To Reproduce**
1. Go to 'admin panel'
2. Click on 'activate proxmox 0.1.0 module'

**Expected behavior**
Installation of the module

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser FF
 - Version 119.0.1

**Additional context**

Hello, i have all the requirment but panel in 0.5.6 is it the problem? tx
![Capture d'écran 2023-11-17 135234](https://github.com/FOSSBilling/Proxmox/assets/1787239/a66d599c-feab-4432-b05a-c767b077d761)

**Comment by sandwitcherz** [comment]
Ok, i have installed whith git and composer install, now, no errors but when i launch install via admin panel, the circle run forever..

**Comment by Anuril** [comment]
I suspect there are left over tables in your database, that's why the install doesn't work. 

We will drop Support for PHP 8.0.X with todays release of PHP 8.3. Also, please make sure to follow [these instructions](https://github.com/FOSSBilling/Proxmox#installation--for-010-preview) if you absolutely want to try out the module. 

As the current state is not able to actually provision VMs, please only install if you want to test and give feedback on the ui and usability.

I'll close this issue in the mean time.
